
-- Seed data for properties table
-- Note: This is a large INSERT statement and might be better handled by a separate script or tool.
-- For demonstration, it's included here.

-- Example of slug generation: convert title to lowercase, replace spaces with hyphens, remove special characters.
-- Example: "Luxury Penthouse with Ocean View" -> "luxury-penthouse-with-ocean-view"

INSERT INTO public.properties (owner_id, title, price, status, type, description, address, latitude, longitude, area, year_built, bedrooms, bathrooms, parking, amenities, images, slug) VALUES
-- Property 1
((SELECT id FROM public.users LIMIT 1),
 'Modern Beachfront Villa', 5500000.00, 'for-sale', 'villa', 'Stunning modern villa with direct beach access and breathtaking ocean views. Features a private infinity pool, state-of-the-art kitchen, and expansive entertainment areas.', '123 Ocean Drive, Miami, FL', 25.7617, -80.1918, 7500, 2020, 5, 6, 4, '["pool", "private beach access", "gym", "smart home system", "jacuzzi"]', '["http://example.com/images/villa1_1.jpg", "http://example.com/images/villa1_2.jpg", "http://example.com/images/villa1_3.jpg", "http://example.com/images/villa1_4.jpg", "http://example.com/images/villa1_5.jpg"]', 'modern-beachfront-villa'),
-- Property 2
((SELECT id FROM public.users LIMIT 1),
 'City Penthouse with Panoramic Views', 3200000.00, 'for-sale', 'penthouse', 'Luxurious penthouse apartment offering unparalleled city views from every room. Modern design with high-end finishes, a gourmet kitchen, and a private rooftop terrace.', '456 Skyline Avenue, New York, NY', 40.7128, -74.0060, 3500, 2018, 4, 5, 2, '["city view", "rooftop terrace", "home office", "wine cellar", "fireplace"]', '["http://example.com/images/penthouse2_1.jpg", "http://example.com/images/penthouse2_2.jpg", "http://example.com/images/penthouse2_3.jpg", "http://example.com/images/penthouse2_4.jpg", "http://example.com/images/penthouse2_5.jpg"]', 'city-penthouse-panoramic-views'),
-- Property 3
((SELECT id FROM public.users LIMIT 1),
 'Secluded Mountain Retreat', 1800000.00, 'for-sale', 'cabin', 'An idyllic mountain retreat surrounded by pristine nature. This cozy yet spacious cabin offers stunning views, a large fireplace, hiking trails, and a serene atmosphere for ultimate relaxation.', '789 Forest Lane, Aspen, CO', 39.1915, -106.8175, 5000, 2015, 3, 3, 3, '["mountain view", "fireplace", "hiking trails", "hot tub", "secluded"]', '["http://example.com/images/cabin3_1.jpg", "http://example.com/images/cabin3_2.jpg", "http://example.com/images/cabin3_3.jpg", "http://example.com/images/cabin3_4.jpg", "http://example.com/images/cabin3_5.jpg"]', 'secluded-mountain-retreat'),
-- Property 4
((SELECT id FROM public.users LIMIT 1),
 'Historic Tuscan Villa', 7200000.00, 'for-sale', 'villa', 'A magnificent historic villa nestled in the heart of Tuscany, Italy. Surrounded by vineyards and olive groves, this property boasts ancient architecture, a private chapel, and panoramic countryside views.', 'Via del Chianti, Florence, IT', 43.7696, 11.2558, 12000, 1600, 8, 9, 10, '["vineyard", "olive grove", "private chapel", "countryside view", "tennis court"]', '["http://example.com/images/villa4_1.jpg", "http://example.com/images/villa4_2.jpg", "http://example.com/images/villa4_3.jpg", "http://example.com/images/villa4_4.jpg", "http://example.com/images/villa4_5.jpg"]', 'historic-tuscan-villa'),
-- Property 5
((SELECT id FROM public.users LIMIT 1),
 'Luxury Family Estate', 9500000.00, 'for-sale', 'estate', 'An expansive luxury estate perfect for large families or entertaining. Features include a grand ballroom, multiple guest houses, a cinema room, a vast garden, and a private sports complex.', '101 Estate Road, Beverly Hills, CA', 34.0901, -118.4019, 25000, 2019, 10, 12, 15, '["guest houses", "cinema room", "grand ballroom", "sports complex", "landscaped gardens"]', '["http://example.com/images/estate5_1.jpg", "http://example.com/images/estate5_2.jpg", "http://example.com/images/estate5_3.jpg", "http://example.com/images/estate5_4.jpg", "http://example.com/images/estate5_5.jpg"]', 'luxury-family-estate'),
-- Property 6
((SELECT id FROM public.users LIMIT 1),
 'Modern Loft in Arts District', 1500000.00, 'for-sale', 'loft', 'Chic industrial loft in the vibrant arts district. Open-concept living, high ceilings, exposed brick, a professional-grade kitchen, and large windows offering city light views.', '202 Art Street, Brooklyn, NY', 40.7000, -73.9500, 2000, 2010, 2, 2, 1, '["industrial design", "exposed brick", "art district", "city lights view", "open concept"]', '["http://example.com/images/loft6_1.jpg", "http://example.com/images/loft6_2.jpg", "http://example.com/images/loft6_3.jpg", "http://example.com/images/loft6_4.jpg", "http://example.com/images/loft6_5.jpg"]', 'modern-loft-arts-district'),
-- Property 7
((SELECT id FROM public.users LIMIT 1),
 'Exclusive Lakeside Residence', 4800000.00, 'for-sale', 'house', 'Serene lakeside residence offering private dock access and stunning water views. Designed for tranquility and luxury, with ample outdoor living spaces and a modern, open-plan interior.', '303 Lakeview Drive, Lake Tahoe, CA', 39.1000, -120.0000, 6000, 2017, 4, 4, 4, '["lake access", "private dock", "water view", "outdoor living", "modern interior"]', '["http://example.com/images/residence7_1.jpg", "http://example.com/images/residence7_2.jpg", "http://example.com/images/residence7_3.jpg", "http://example.com/images/residence7_4.jpg", "http://example.com/images/residence7_5.jpg"]', 'exclusive-lakeside-residence'),
-- Property 8
((SELECT id FROM public.users LIMIT 1),
 'Tropical Island Paradise', 12000000.00, 'for-sale', 'resort', 'Own a piece of paradise with this ultra-luxury island resort. Features private villas, white-sand beaches, crystal-clear waters, a world-class spa, and gourmet dining experiences.', 'Private Island, Maldives', 3.2000, 73.0000, 50000, 2022, 15, 18, 20, '["private island", "white sand beach", "infinity pools", "spa", "gourmet dining"]', '["http://example.com/images/island8_1.jpg", "http://example.com/images/island8_2.jpg", "http://example.com/images/island8_3.jpg", "http://example.com/images/island8_4.jpg", "http://example.com/images/island8_5.jpg"]', 'tropical-island-paradise'),
-- Property 9
((SELECT id FROM public.users LIMIT 1),
 'Charming Countryside Estate', 2500000.00, 'for-sale', 'estate', 'A picturesque countryside estate offering peace and privacy. Includes a main manor, carriage house, landscaped gardens, stables, and miles of private walking trails.', '404 Country Road, Rural VA', 38.0000, -78.5000, 10000, 1900, 6, 5, 6, '["carriage house", "stables", "landscaped gardens", "walking trails", "fireplace"]', '["http://example.com/images/estate9_1.jpg", "http://example.com/images/estate9_2.jpg", "http://example.com/images/estate9_3.jpg", "http://example.com/images/estate9_4.jpg", "http://example.com/images/estate9_5.jpg"]', 'charming-countryside-estate'),
-- Property 10
((SELECT id FROM public.users LIMIT 1),
 'Sleek Urban Apartment', 980000.00, 'for-sale', 'apartment', 'A sleek and modern apartment in the heart of the city. Features minimalist design, smart home technology, a private balcony, and access to building amenities like a fitness center and concierge.', '505 City Center Blvd, Chicago, IL', 41.8781, -87.6298, 1500, 2019, 2, 2, 1, '["smart home", "private balcony", "fitness center", "concierge", "minimalist design"]', '["http://example.com/images/apartment10_1.jpg", "http://example.com/images/apartment10_2.jpg", "http://example.com/images/apartment10_3.jpg", "http://example.com/images/apartment10_4.jpg", "http://example.com/images/apartment10_5.jpg"]', 'sleek-urban-apartment'),
-- Property 11
((SELECT id FROM public.users LIMIT 1),
 'Vineyard Estate with Winery', 15000000.00, 'for-sale', 'estate', 'An exceptional estate featuring a working vineyard and a boutique winery. The property includes a grand main residence, wine cellar, tasting room, and picturesque rolling hills.', '606 Wine Route, Napa Valley, CA', 38.5000, -122.3000, 40000, 1890, 7, 8, 12, '["vineyard", "winery", "wine cellar", "tasting room", "rolling hills"]', '["http://example.com/images/estate11_1.jpg", "http://example.com/images/estate11_2.jpg", "http://example.com/images/estate11_3.jpg", "http://example.com/images/estate11_4.jpg", "http://example.com/images/estate11_5.jpg"]', 'vineyard-estate-winery'),
-- Property 12
((SELECT id FROM public.users LIMIT 1),
 'Luxury Ski Chalet', 4200000.00, 'for-sale', 'chalet', 'A magnificent ski chalet offering unparalleled luxury and access to world-class slopes. Features include a private spa, home theater, gourmet kitchen, and stunning mountain vistas.', '707 Snowpeak Lane, Whistler, BC', 50.1163, -122.9574, 4500, 2021, 4, 5, 3, '["ski-in ski-out", "private spa", "home theater", "mountain view", "fireplace"]', '["http://example.com/images/chalet12_1.jpg", "http://example.com/images/chalet12_2.jpg", "http://example.com/images/chalet12_3.jpg", "http://example.com/images/chalet12_4.jpg", "http://example.com/images/chalet12_5.jpg"]', 'luxury-ski-chalet'),
-- Property 13
((SELECT id FROM public.users LIMIT 1),
 'Eco-Friendly Rainforest Home', 950000.00, 'for-sale', 'house', 'A sustainable and eco-friendly home nestled within a lush rainforest. Designed with natural materials, solar power, and rainwater harvesting, offering a unique connection to nature.', '808 Jungle Trail, Costa Rica', 9.7489, -83.7534, 3000, 2016, 3, 3, 2, '["eco-friendly", "rainforest view", "solar power", "rainwater harvesting", "natural materials"]', '["http://example.com/images/rainforest13_1.jpg", "http://example.com/images/rainforest13_2.jpg", "http://example.com/images/rainforest13_3.jpg", "http://example.com/images/rainforest13_4.jpg", "http://example.com/images/rainforest13_5.jpg"]', 'eco-friendly-rainforest-home'),
-- Property 14
((SELECT id FROM public.users LIMIT 1),
 'Charming Waterfront Cottage', 1100000.00, 'for-sale', 'cottage', 'A picturesque waterfront cottage offering serene views and direct water access. Features a cozy interior, private dock, and beautiful garden.', '909 Lakeside Path, Ontario, CA', 43.6532, -79.3832, 1800, 1980, 3, 2, 2, '["waterfront", "private dock", "garden", "lake view", "cozy"]', '["http://example.com/images/cottage14_1.jpg", "http://example.com/images/cottage14_2.jpg", "http://example.com/images/cottage14_3.jpg", "http://example.com/images/cottage14_4.jpg", "http://example.com/images/cottage14_5.jpg"]', 'charming-waterfront-cottage'),
-- Property 15
((SELECT id FROM public.users LIMIT 1),
 'Luxury Equestrian Estate', 18000000.00, 'for-sale', 'estate', 'An unparalleled equestrian estate designed for horse lovers. Features a grand manor, state-of-the-art stables, riding arenas, riding trails, and expansive pastures.', '1010 Horseback Ridge, Lexington, KY', 38.0406, -84.5037, 100000, 2005, 8, 10, 20, '["stables", "riding arena", "riding trails", "pastures", "equestrian facilities"]', '["http://example.com/images/equestrian15_1.jpg", "http://example.com/images/equestrian15_2.jpg", "http://example.com/images/equestrian15_3.jpg", "http://example.com/images/equestrian15_4.jpg", "http://example.com/images/equestrian15_5.jpg"]', 'luxury-equestrian-estate'),
-- Property 16
((SELECT id FROM public.users LIMIT 1),
 'Mediterranean Villa with Sea View', 6200000.00, 'for-sale', 'villa', 'An exquisite Mediterranean villa perched on a cliffside, offering stunning sea views. Boasts classic architecture, spacious terraces, a private pool, and lush gardens.', '111 Azure Coast, Santorini, GR', 36.3932, 25.4615, 8000, 2010, 5, 7, 5, '["sea view", "cliffside", "private pool", "terrace", "mediterranean architecture"]', '["http://example.com/images/villa16_1.jpg", "http://example.com/images/villa16_2.jpg", "http://example.com/images/villa16_3.jpg", "http://example.com/images/villa16_4.jpg", "http://example.com/images/villa16_5.jpg"]', 'mediterranean-villa-sea-view'),
-- Property 17
((SELECT id FROM public.users LIMIT 1),
 'Urban Oasis Apartment', 1100000.00, 'for-sale', 'apartment', 'A tranquil urban oasis apartment offering a peaceful retreat from the city bustle. Features a private garden, serene interior design, and access to exclusive resident amenities.', '1212 Garden Lane, San Francisco, CA', 37.7749, -122.4194, 1600, 2018, 3, 3, 1, '["private garden", "urban oasis", "serene design", "resident amenities", "quiet retreat"]', '["http://example.com/images/apartment17_1.jpg", "http://example.com/images/apartment17_2.jpg", "http://example.com/images/apartment17_3.jpg", "http://example.com/images/apartment17_4.jpg", "http://example.com/images/apartment17_5.jpg"]', 'urban-oasis-apartment'),
-- Property 18
((SELECT id FROM public.users LIMIT 1),
 'Exclusive Golf Course Residence', 7800000.00, 'for-sale', 'residence', 'A prestigious residence located directly on a championship golf course. Offers spectacular views, meticulously landscaped grounds, a private clubhouse, and luxurious living spaces.', '1313 Fairway Drive, Scottsdale, AZ', 33.4942, -111.9261, 9000, 2017, 5, 6, 6, '["golf course view", "private clubhouse", "landscaped grounds", "luxury living", "guest house"]', '["http://example.com/images/residence18_1.jpg", "http://example.com/images/residence18_2.jpg", "http://example.com/images/residence18_3.jpg", "http://example.com/images/residence18_4.jpg", "http://example.com/images/residence18_5.jpg"]', 'exclusive-golf-course-residence'),
-- Property 19
((SELECT id FROM public.users LIMIT 1),
 'Art Deco Masterpiece', 4700000.00, 'for-sale', 'apartment', 'A stunning Art Deco apartment meticulously restored to its former glory. Features intricate detailing, grand living spaces, a chef''s kitchen, and period-accurate fixtures.', '1414 Deco Avenue, New York, NY', 40.7500, -73.9800, 2500, 1930, 3, 4, 1, '["art deco", "restored", "period fixtures", "chef kitchen", "grand interiors"]', '["http://example.com/images/artdeco19_1.jpg", "http://example.com/images/artdeco19_2.jpg", "http://example.com/images/artdeco19_3.jpg", "http://example.com/images/artdeco19_4.jpg", "http://example.com/images/artdeco19_5.jpg"]', 'art-deco-masterpiece'),
-- Property 20
((SELECT id FROM public.users LIMIT 1),
 'Remote Wilderness Lodge', 3100000.00, 'for-sale', 'lodge', 'An exclusive wilderness lodge offering unparalleled access to nature. Features a rustic yet luxurious design, private trails, stunning wildlife views, and a focus on sustainable living.', '1515 Wilderness Road, Montana', 47.0000, -110.0000, 8000, 2012, 4, 4, 5, '["wilderness", "wildlife", "private trails", "sustainable living", "rustic luxury"]', '["http://example.com/images/lodge20_1.jpg", "http://example.com/images/lodge20_2.jpg", "http://example.com/images/lodge20_3.jpg", "http://example.com/images/lodge20_4.jpg", "http://example.com/images/lodge20_5.jpg"]', 'remote-wilderness-lodge'),
-- Property 21
((SELECT id FROM public.users LIMIT 1),
 'Coastal Smart Home', 2900000.00, 'for-sale', 'house', 'A state-of-the-art smart home with breathtaking coastal views. Integrated technology controls lighting, climate, security, and entertainment, all accessible via a mobile app.', '1616 Coastline Drive, Malibu, CA', 34.0300, -118.7700, 4000, 2020, 4, 5, 3, '["smart home", "coastal view", "mobile app control", "infinity pool", "home theater"]', '["http://example.com/images/smarthome21_1.jpg", "http://example.com/images/smarthome21_2.jpg", "http://example.com/images/smarthome21_3.jpg", "http://example.com/images/smarthome21_4.jpg", "http://example.com/images/smarthome21_5.jpg"]', 'coastal-smart-home'),
-- Property 22
((SELECT id FROM public.users LIMIT 1),
 'Urban Loft with Creative Space', 1700000.00, 'for-sale', 'loft', 'A spacious urban loft designed for creatives, featuring an open-plan layout, ample natural light, a dedicated studio space, and modern amenities.', '1717 Creative Way, Los Angeles, CA', 34.0522, -118.2437, 2800, 2015, 3, 3, 2, '["creative space", "open plan", "natural light", "studio space", "urban loft"]', '["http://example.com/images/loft22_1.jpg", "http://example.com/images/loft22_2.jpg", "http://example.com/images/loft22_3.jpg", "http://example.com/images/loft22_4.jpg", "http://example.com/images/loft22_5.jpg"]', 'urban-loft-creative-space'),
-- Property 23
((SELECT id FROM public.users LIMIT 1),
 'Tranquil Riverside Residence', 2100000.00, 'for-sale', 'house', 'A peaceful residence situated along a scenic river, offering tranquil views and direct river access. Features elegant interiors, expansive gardens, and private boat dock.', '1818 River Road, Austin, TX', 30.2672, -97.7431, 3800, 2017, 4, 4, 3, '["riverside", "river access", "private boat dock", "gardens", "tranquil views"]', '["http://example.com/images/riverside23_1.jpg", "http://example.com/images/riverside23_2.jpg", "http://example.com/images/riverside23_3.jpg", "http://example.com/images/riverside23_4.jpg", "http://example.com/images/riverside23_5.jpg"]', 'tranquil-riverside-residence'),
-- Property 24
((SELECT id FROM public.users LIMIT 1),
 'Luxury Ski-In/Ski-Out Condo', 2800000.00, 'for-sale', 'condo', 'A premier ski-in/ski-out condominium offering ultimate convenience and luxury on the slopes. Features modern amenities, stunning mountain views, and easy access to ski lifts and village amenities.', '1919 Slope Side, Vail, CO', 39.6401, -106.3732, 1800, 2019, 3, 3, 1, '["ski-in ski-out", "mountain view", "near ski lifts", "modern amenities", "balcony"]', '["http://example.com/images/condo24_1.jpg", "http://example.com/images/condo24_2.jpg", "http://example.com/images/condo24_3.jpg", "http://example.com/images/condo24_4.jpg", "http://example.com/images/condo24_5.jpg"]', 'luxury-ski-in-ski-out-condo'),
-- Property 25
((SELECT id FROM public.users LIMIT 1),
 'Historic Townhouse in Paris', 5800000.00, 'for-sale', 'townhouse', 'A magnificent historic townhouse located in the heart of Paris. This elegant property features classic Parisian architecture, ornate interiors, a private courtyard, and is steps away from iconic landmarks.', '2020 Rue de Rivoli, Paris, FR', 48.8566, 2.3522, 3000, 1850, 5, 6, 2, '["historic", "private courtyard", "parisian architecture", "central location", "ornate interiors"]', '["http://example.com/images/townhouse25_1.jpg", "http://example.com/images/townhouse25_2.jpg", "http://example.com/images/townhouse25_3.jpg", "http://example.com/images/townhouse25_4.jpg", "http://example.com/images/townhouse25_5.jpg"]', 'historic-townhouse-paris'),
-- Property 26
((SELECT id FROM public.users LIMIT 1),
 'Desert Modern Estate', 4500000.00, 'for-sale', 'estate', 'A striking modern estate designed to blend seamlessly with its desert surroundings. Features clean lines, expansive glass walls, a private oasis pool, and unparalleled desert vistas.', '2121 Desert Way, Palm Springs, CA', 33.8354, -116.5413, 7000, 2019, 4, 5, 4, '["desert view", "modern design", "private oasis pool", "expansive glass", "fire pit"]', '["http://example.com/images/estate26_1.jpg", "http://example.com/images/estate26_2.jpg", "http://example.com/images/estate26_3.jpg", "http://example.com/images/estate26_4.jpg", "http://example.com/images/estate26_5.jpg"]', 'desert-modern-estate'),
-- Property 27
((SELECT id FROM public.users LIMIT 1),
 'Luxury Farmhouse Estate', 6800000.00, 'for-sale', 'estate', 'A sophisticated farmhouse estate offering a blend of rustic charm and modern luxury. Features include vast acreage, equestrian facilities, a gourmet kitchen, and private walking trails.', '2222 Farm Road, Sonoma, CA', 38.2914, -122.4582, 50000, 1920, 7, 7, 10, '["farmhouse", "equestrian facilities", "vast acreage", "private trails", "gourmet kitchen"]', '["http://example.com/images/farmhouse27_1.jpg", "http://example.com/images/farmhouse27_2.jpg", "http://example.com/images/farmhouse27_3.jpg", "http://example.com/images/farmhouse27_4.jpg", "http://example.com/images/farmhouse27_5.jpg"]', 'luxury-farmhouse-estate'),
-- Property 28
((SELECT id FROM public.users LIMIT 1),
 'Zen Garden Retreat Villa', 3900000.00, 'for-sale', 'villa', 'A serene villa inspired by Zen philosophy, featuring tranquil courtyards, minimalist design, a private meditation garden, and natural water features.', '2323 Zen Lane, Kyoto, JP', 35.0116, 135.7681, 4000, 2017, 3, 4, 3, '["zen garden", "meditation room", "minimalist design", "water features", "tranquil"]', '["http://example.com/images/zenvilla28_1.jpg", "http://example.com/images/zenvilla28_2.jpg", "http://example.com/images/zenvilla28_3.jpg", "http://example.com/images/zenvilla28_4.jpg", "http://example.com/images/zenvilla28_5.jpg"]', 'zen-garden-retreat-villa'),
-- Property 29
((SELECT id FROM public.users LIMIT 1),
 'Seaside Family Home', 1600000.00, 'for-sale', 'house', 'A charming family home located just steps from the beach. Offers ocean breezes, a spacious backyard, modern updates, and is perfect for raising a family by the sea.', '2424 Beachfront Ave, San Diego, CA', 32.7157, -117.1611, 2500, 1995, 4, 3, 2, '["near beach", "ocean breeze", "spacious backyard", "family friendly", "modern updates"]', '["http://example.com/images/seaside29_1.jpg", "http://example.com/images/seaside29_2.jpg", "http://example.com/images/seaside29_3.jpg", "http://example.com/images/seaside29_4.jpg", "http://example.com/images/seaside29_5.jpg"]', 'seaside-family-home'),
-- Property 30
((SELECT id FROM public.users LIMIT 1),
 'Luxury Smart Apartment with City View', 2500000.00, 'for-sale', 'apartment', 'A sophisticated smart apartment offering panoramic city views and cutting-edge technology. Features automated systems, a private balcony, high-end finishes, and access to exclusive building amenities.', '2525 Skyhigh Road, London, UK', 51.5074, -0.1278, 2000, 2021, 3, 3, 1, '["smart home", "city view", "private balcony", "high-end finishes", "concierge service"]', '["http://example.com/images/apartment30_1.jpg", "http://example.com/images/apartment30_2.jpg", "http://example.com/images/apartment30_3.jpg", "http://example.com/images/apartment30_4.jpg", "http://example.com/images/apartment30_5.jpg"]', 'luxury-smart-apartment-city-view');
